services:
  - type: web
    name: streamme
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production